"""
Test file for ROman Converter.
"""
import csv

from choco.converters.roman_converter import decompose_roman, convert_roman_numeral


def test_roman_conversion(stats_file):
    """
    Tests the chord converter using the statistics file generated by stats.py.
    """
    with open(stats_file) as csv_file:
        stats = csv.reader(csv_file, delimiter=',')

        for i, chord_data in enumerate(stats):
            if i != 0:
                # check if the chord is decomposed correctly
                processed_chord = decompose_roman(chord_data[0])
                k = ' '.join(processed_chord[0])
                ch = ''.join(processed_chord[1])
                root = f"/{'/'.join([x for x in processed_chord[2]])}" if len(processed_chord[2]) > 0 else ''
                if f'{k}:{ch}{root}' == chord_data[0]:
                    pass
                # print(processed_chord)
                converted_chord = convert_roman_numeral(processed_chord)
                print(converted_chord)


if '__main__' == __name__:
    test_roman_conversion('../../partitions/when-in-rome/choco/chord_stats.csv')
