"""
Test file for Roman Converter.
"""

from converter_utils import open_stats_file
from roman_converter import convert_roman


def test_roman_conversion(stats_file) -> None:
    """
    Tests the chord converter using the statistics file generated by stats.py.
    """
    stats = open_stats_file(stats_file)
    for i, chord_data in enumerate(stats):
        # check if the chord is decomposed correctly
        print(chord_data[0])
        try:
            converted_chord = convert_roman(chord_data[0])
            print(converted_chord)
        except ValueError as ve:
            print(ve)


if "__main__" == __name__:
    test_roman_conversion("../../../partitions/jazz-corpus/choco/chord_stats.csv")
