PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>

CONSTRUCT {    
    ?s xyz:namespace ?namespace .
    ?s xyz:sandbox ?sandbox .
    ?s xyz:data ?annotation . 
    ?s xyz:annotation_metadata [
        xyz:annotation_tools ?tools ;
        xyz:curator [ xyz:name ?curator_name ;
                        xyz:email ?curator_email ] ;
        xyz:annotator ?annotator ;
        xyz:version ?version ;
        xyz:corpus ?corpus ;
        xyz:annotation_rules ?annotation_rules ;
        xyz:validation ?validation ;
        xyz:data_source ?data_source 
    ] .

    ?annotation a xyz:Annotation ;
        xyz:value ?value ;
        xyz:time ?time ;
        xyz:confidence ?confidence ;
        xyz:duration ?duration .
    

}
WHERE {
    SERVICE <x-sparql-anything:file:///Users/amp/src/choco/partitions/jaah/choco/jams/jaah_93.json> {        
        ?s xyz:namespace ?namespace .
        ?s xyz:sandbox ?sandbox .
        ?s xyz:annotation%5Fmetadata ?metadata .
        ?metadata xyz:annotation%5Ftools ?tools .
        ?metadata xyz:curator ?curator .
        ?curator xyz:name ?curator_name .
        ?curator xyz:email ?curator_email .
        ?metadata xyz:annotator ?annotator .
        ?metadata xyz:version ?version .
        ?metadata xyz:corpus ?corpus .
        ?metadata xyz:annotation%5Frules ?annotation_rules .
        ?metadata xyz:validation ?validation .
        ?metadata xyz:data%5Fsource ?data_source .
        ?s xyz:data ?o .
        ?o fx:anySlot ?annotation .
        ?annotation xyz:value ?value .
        ?annotation xyz:time ?time .
        ?annotation xyz:confidence ?confidence .
        ?annotation xyz:duration ?duration .

    }
}