# Copyright (c) 2007 Andrew Choi.  All rights reserved.

# This is emphatically NOT free/GPL software.

# Permission for the use of this code is granted only for research,
# educational, and non-commercial purposes.

# Redistribution of this code or its parts in any form without
# permission, with or without modification, is prohibited.
# Modifications include, but are not limited to, translation to other
# programming languages and reuse of tables, constant definitions, and
# API's defined in it.

# There is no restriction on the use of the output generated by this
# software.

# THIS SOFTWARE IS PROVIDED BY ANDREW CHOI "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED.  IN NO EVENT SHALL ANDREW CHOI BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


from choco.parsers.py_biab_converter.objects import ScaleType

ScaleType.define('major', ':2.3.4.5.6.7')
ScaleType.define('harmonic minor', ':2.b3.4.5.b6.7')
ScaleType.define('melodic minor', ':2.b3.4.5.6.7')
# ScaleType.define('natural minor', ':2.b3.4.5.b6.b7')
# ScaleType.define('altered', ':b2.#2.3.b5.#5.b7')
ScaleType.define('diminished', ':b2.#2.3.b5.5.6.b7')
ScaleType.define('whole tone', ':2.3.b5.#5.b7')
ScaleType.define('super locrian', ':b2.#2.3.b5.#5.b7')
# ScaleType.define('blues', ':b3.3.4.#4.5.b7')
# ScaleType.define('bebop dominant', ':2.3.4.5.6.b7.7')
